name: CRD Version Updater

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      install_alertmanagerconfigs:
        type: boolean
        default: false
      install_alertmanagers:
        type: boolean
        default: false
      install_podmonitors:
        type: boolean
        default: false
  
    # secrets:
    #   token:
    #     required: true
      
      # dest:
      #   required: true
      #   type: string

jobs:
  data-fetch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
            ref: ${{ github.head_ref }}
            fetch-depth: 0 
        
      - name: download the CRD
        if: ${{ inputs.install_podmonitors == true }}
        run: |
            curl -sS https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v${{ inputs.version }}/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml > version_file
            cat version_file

      - name: commit 
        env:
          GH_TOKEN: ${{ secrets.token }}
        run: |
          git config --global user.email "stanleyikegwuonu@gmail.com"
          git config --global user.name "jstan-isch"
          git add version_file
          git commit -m "crd version update - v${{ inputs.version }}"
          git push
          # git push origin HEAD

      # - name: commit the data
      #   uses: EndBug/add-and-commit@v9 
      #   with: 
      #     message: 'Version update ${{ inputs.version }}'
