name: CRD Version Updater

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      # dest:
      #   required: true
      #   type: string

jobs:
  data-fetch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
            ref: ${{ github.head_ref }}
            fetch-depth: 0 
        
      - name: download the CRD
        run: |
            curl -sS https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v${{ inputs.version }}/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml > version_file

      - name: commit the data
        uses: EndBug/add-and-commit@v9 
        with: 
          message: 'Version update ${{ inputs.version }}'
