name: CRD Version Updater

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      crd_alertmanagerconfigs:
        type: boolean
        default: false
      crd_alertmanagers:
        type: boolean
        default: false
      crd_podmonitors:
        type: boolean
        default: false

jobs:
  data-fetch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
            ref: ${{ github.head_ref }}
            fetch-depth: 0 

      - name: sort
        run: |
          declare -A input_values=(
            ["alertmanagerconfigs"]=${{ inputs.crd_alertmanagerconfigs }}
            ["alertmanagers"]=${{ inputs.crd_alertmanagers }}
            ["podmonitors"]=${{ inputs.crd_podmonitors }}
          )

          for key in "${!input_values[@]}"; do
            if [ "${input_values[$key]}" == true ]; then
              curl -sS https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.70.0/example/prometheus-operator-crd/monitoring.coreos.com_"$key".yaml > "crd_$key.yaml"
            fi
          done
        
      # - name: download the CRD
      #   run: |
      #     for key in "${!input_values[@]}"; do
      #       if [ "${input_values[$key]}" == true ]; then
      #           # echo "$key: ${input_values[$key]}"
      #           curl -sS https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v${{ inputs.version }}/example/prometheus-operator-crd/monitoring.coreos.com_"$key".yaml >> version_file
      #       fi
      #     done
      #     # curl -sS https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v${{ inputs.version }}/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml > version_file
      #     # cat version_file

      - name: commit 
        # env:
        #   GH_TOKEN: ${{ secrets.token }}
        run: |
          git config --global user.email "stanleyikegwuonu@gmail.com"
          git config --global user.name "jstan-isch"
          git add -A
          git commit -m "crd version update - v${{ inputs.version }}"
          git push
          # git push origin HEAD

      # - name: commit the data
      #   uses: EndBug/add-and-commit@v9 
      #   with: 
      #     message: 'Version update ${{ inputs.version }}'
