name: Try Log Secrets

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
    
     
     

jobs:
  log:
    runs-on: ubuntu-latest
    env:
      SECRET_CONTEXT: ${{ toJSON(secrets) }}

    steps:
      - name: Log the secret
        run: |
          echo "Value of MY_SECRET1: $MY_SECRET1"
          echo ${{ secrets.MY_SECRET }}
          echo ${{ secrets.MY_SECRET }} | sed 's/./&/g' 
        
      
      - name: expose secret
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          to_envs() { jq -r "to_entries[] | \"\(.key)<<$EOF\n\(.value)\n$EOF\n\""; }
          echo "$SECRETS_CONTEXT" | to_envs >> $GITHUB_ENV
      
